# Note that because of how the containers are set up, the files passed must be
# contained within the working directory. To change this, edit the
# `run_container.sh` script which calls the docker/singularity container for
# all steps.
#
# GENOTYPES: PLINK 2 (.pgen/.pvar/.psam) is RECOMMENDED -- it is what the
# All of Us runs used, it is smaller, and the SAIGE image reads it directly.
# PLINK 1 (.bed/.bim/.fam) also works. A VCF is REFUSED: convert it once,
#     resources/plink2 --vcf exome.chr20.vcf.gz --make-pgen --out exome.chr20
# rather than paying for a conversion on every chromosome of every phenotype.

# Which chromosome to analyse. Spell it as the .pvar/.bim does: if the first
# column reads '20', --chr chr20 will not work (but --chr 20 will).
chrom=["chr20"]

# Plink 2 filename prefix of .pgen/.pvar/.psam for WES (or WGS restricted to
# exons). Relative to, and contained in, the current working directory.
pgen=["path/to/pgen/files"]
# ... or the Plink 1 prefix of .bed/.bim/.fam, if that is what you have.
plink=["path/to/plink/files"]

# Model file and variance-ratio file from SAIGE step 1: ${out_step1}.rda and
# ${out_step1}.varianceRatio.txt, relative to the current working directory.
model_file=["/path/to/model/file"]
variance_ratio=["/path/to/varianceratio"]

# Variant annotations (the BRaVa group file), generated here:
# https://github.com/BRaVa-genetics/variant-annotation
group_file=["/path/to/group_file"]
# The masks for the SAIGE-GENE+ run, ':' joining labels into one mask and
# ',' separating masks. Every label must appear in the group file, or step 2
# refuses the run and lists the labels the file has: change them here.
annots="pLoF,damaging_missense_or_protein_altering,other_missense_or_protein_altering,synonymous,pLoF:damaging_missense_or_protein_altering,pLoF:damaging_missense_or_protein_altering:other_missense_or_protein_altering:synonymous"

# Output prefix for the data generated by this step (step 2).
out_step2=["out"]

# is singularity (or apptainer) available? If not, it is assumed that docker is available.
IS_SINGULARITY={"false","true"}

# The GRM from step 0 and its sample IDs:
# ${out_step0}_relatednessCutoff_0.05_5000_randomMarkersUsed.sparseGRM.mtx and
# the same with .sampleIDs.txt appended.
GRM=["path/to/GRM/file"]
GRM_samples=["path/to/GRM/sampleID/file"]

# ---- 1. single-variant tests ------------------------------------------------
bash 02_step2_SPAtests_variant_and_gene.sh \
    --chr $chrom \
    --testType variant \
    --pgen ${pgen} \
    --modelFile ${model_file} \
    --varianceRatio ${variance_ratio} \
    --outputPrefix ${out_step2}.variant \
    --isSingularity $IS_SINGULARITY \
    --sparseGRM ${GRM} \
    --sparseGRMID ${GRM_samples}

# ---- 2. SAIGE-GENE+ group tests (six masks x three max MAFs, SKAT-O) --------
bash 02_step2_SPAtests_variant_and_gene.sh \
    --chr $chrom \
    --testType group \
    --pgen ${pgen} \
    --modelFile ${model_file} \
    --varianceRatio ${variance_ratio} \
    --groupFile ${group_file} \
    --annotations ${annots} \
    --outputPrefix ${out_step2}.skato \
    --isSingularity $IS_SINGULARITY \
    --sparseGRM ${GRM} \
    --sparseGRMID ${GRM_samples}

# ---- 3. FlexRV (one run per weight set) -------------------------------------
# The group file for a weight set is built ONCE per chromosome by
# 04_flexrv_groupfile.sh (AlphaMissense first; a second weight set the same
# way under another name). One mask, one max MAF (0.001), burden statistic;
# the run writes every transform set's row and the pooled p_FlexRV row.
flexrv_group_file_AM=["/path/to/group_file.flexrv_AM.txt"]
bash 02_step2_SPAtests_variant_and_gene.sh \
    --chr $chrom \
    --pgen ${pgen} \
    --modelFile ${model_file} \
    --varianceRatio ${variance_ratio} \
    --groupFile ${flexrv_group_file_AM} \
    --flexRVscore AM \
    --outputPrefix ${out_step2}.flexrv_AM \
    --isSingularity $IS_SINGULARITY \
    --sparseGRM ${GRM} \
    --sparseGRMID ${GRM_samples}

# With --plink instead of --pgen for PLINK 1 genotypes. If step 1 was fitted at
# a relatedness cutoff other than 0.05, add --relatednessCutoff <that value>.
