# Note that because of how the containers are set up, the files passed must be
# contained within the working directory. To change this, edit the
# `run_container.sh` script which calls the docker/singularity container for
# all steps.

TRAIT_TYPE={"quantitative","binary"}

# Path to the plink files created by step 0 (used to generate the variance
# ratio). It will be of the form ${out_step0}.plink_for_var_ratio.{bim,bed,fam}
# where ${out_step0} is the output prefix to data generated by step 0.
# (A PLINK 2 prefix can be given instead with --genotypePgen.)
plink_for_var_ratio=["path/to/varianceratio/plink/files"]

# The fit gates of the SAIGE image are ON: a binary trait with fewer than 100
# cases, a categorical covariate level with fewer than 10 cases or controls, a
# separated covariate model or a fit that did not converge is REFUSED with the
# gate named in the log. That is the intended answer for such a trait.

# Path to the phenotype file. This file should be tab delimited, contain
# column names, and a column of sample IDs that matches the sample IDs of the
# genetic data. 
# Note that the phenotype file must also contain all of the covariates.
# Make sure not to include spaces or strange characters in the column names.
pheno_file=["path/to/phenotype/file"]

# The column name for the phenotype to be analysed - this must match exactly!
pheno=["pheno_col"]

# Comma separated (without spaces!) list of covariates. These covariate names
# must exactly match the corresponding column names in ${pheno_file}.
# 20 PCs, as All of Us used; the number of PCs is the biobank's choice.
covariates=["age,age2,age_sex,age2_sex,sex,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20"]
# Comma separated (without spaces!) list of categorical covariates
# If a categorical variable is to be included as a covariate, it should be
# included in both ${covariates} and ${categorical_covariates}. 
categorical_covariates=["sex"]

# For a SEX-SPECIFIC trait, drop every sex term, as All of Us did: covariates
# "age,age2,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20", no categorical covariates, and
# add --sex F (or M) to the call below. The other sex's phenotype must be
# missing (NA) in ${pheno_file}; step 1 refuses the trait otherwise.

# Optional! Path to a sample ID file. This should be a single column of sample
# IDs, with no header. The code will simply restrict the phenotype file to 
# these samples.
sample_id_path=["path/to/sampleIDs"]

# The column name for containing the sample IDs - this must match exactly!
# Note: the default is IID.
sample_id_col=["IID"]

# Output prefix for the data generated by this step (step 1).
out_step1=["out"]

# is singularity (or apptainer) available? If not, it is assumed that docker is available.
IS_SINGULARITY={"false","true"}

# Path to the GRM file created by step 0.
# It will be of the form 
# ${out_step0}_relatednessCutoff_${relatedness_cutoff}_5000_randomMarkersUsed.sparseGRM.mtx where
# ${out_step0} is the output prefix to data generated by step 0. 
GRM=["path/to/GRM/file"]

# Path to the GRM sample IDs file created by step 0.
# It will be of the form 
# ${out_step0}_relatednessCutoff_${relatedness_cutoff}_5000_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt
# where ${out_step0} is the output prefix to data generated by step 0.
GRM_samples=["path/to/GRM/sampleID/file"]

# The relatedness cutoff step 0 built the GRM at; the same value goes to step 2.
relatedness_cutoff=0.05

bash 01_step1_fitNULLGLMM.sh \
    --traitType ${TRAIT_TYPE} \
    --genotypePlink ${plink_for_var_ratio} \
    --phenoFile ${pheno_file} \
    --phenoCol ${pheno} \
    --covarColList ${covariates} \
    --categCovarColList ${categorical_covariates} \
    --sampleIDs ${sample_id_path} \
    --sampleIDCol ${sample_id_col} \
    --outputPrefix ${out_step1} \
    --isSingularity ${IS_SINGULARITY} \
    --sparseGRM ${GRM} \
    --sparseGRMID ${GRM_samples} \
    --relatednessCutoff ${relatedness_cutoff}

# A sparse GRM with more than 100 relatives per sample on average is refused
# (the fit can run for hours or never finish): rerun step 0 with a higher
# relatedness_cutoff. Only if that is not an option, add --forceDenseGRM.

