# Note that because of how the containers are set up, the files passed must be
# contained within the working directory. To change this, edit the
# `run_container.sh` script which calls the docker/singularity container for
# all steps.

# All files contained within --geneticDataDirectory of the type flagged by
# --geneticDataFormat will be globbed AND MERGED, so give this step a directory
# of its own: all of the autosomes for just one biobank/cohort, and not the
# exome files step 2 reads.
genetic_data_directory=["in/genotypes/"]

# PLINK 2 (.pgen/.pvar/.psam), RECOMMENDED, or PLINK 1 (.bed/.bim/.fam) if that
# is what your array data is in. A VCF is refused: convert it once with
#   resources/plink2 --vcf FILE.vcf.gz --make-pgen --out PREFIX
GENETIC_DATA_FORMAT={"pgen","plink"}

GENETIC_DATA_TYPE={"WES","WGS","genotype"}

# is singularity (or apptainer) available? If not, it is assumed that docker is available.
IS_SINGULARITY={"false","true"}

# Output prefix for the data generated by this step (step 0).
out_step0=["out"]

# These are the sampleIDs (single column) to be used to define the GRM.
# To use all of the samples in the files, DELETE the --sampleIDs line below
# (an empty value is refused: it would swallow the next flag).
sample_id_path=["path/to/sampleIDs"]

# Relatedness cutoff: GRM entries below it are dropped. Use the SAME value in
# steps 1, 2 and 3. 0.05 is the default; All of Us used 0.125 for its admixed amr
# cohort, whose GRM was too dense to fit at 0.05. Steps 0 and 1 print the
# GRM's relatives per sample and warn loudly when it is dense: raise it then.
relatedness_cutoff=0.05

# The inclusion of the following two flags ensures that the variance ratio file
# and GRM files are created.
# --generate_plink_for_vr (used in step 1 and flagged by --genotypePlink).
# --generate_GRM (used in step 1 and flagged by --sparseGRM and --sparseGRMID).

bash 00_step0_VR_and_GRM.sh \
    --geneticDataDirectory ${genetic_data_directory} \
    --geneticDataFormat ${GENETIC_DATA_FORMAT} \
    --geneticDataType ${GENETIC_DATA_TYPE} \
    --isSingularity ${IS_SINGULARITY} \
    --outputPrefix ${out_step0} \
    --sampleIDs ${sample_id_path} \
    --relatednessCutoff ${relatedness_cutoff} \
    --generate_plink_for_vr \
    --generate_GRM
